all: $(GLIB_GIRFILES)

$(GLIB_GIRFILES): %.gir: build/gobject-introspection/%.gir
	install -m644 $< $@

define build_gir
	$(PKG_CONFIG_ENVIRONMENT) $(MAKE) -C build/gobject-introspection $(notdir $@)
endef

build/gobject-introspection/GLib-2.0.gir: \
    src/gobject-introspection/gir/glib-2.0.c \
    src/glib/glib/*.h \
    src/glib/gobject/glib-types.h
	$(build_gir)

build/gobject-introspection/GObject-2.0.gir: \
    src/gobject-introspection/gir/gobject-2.0.c \
    $(filter-out src/glib/gobject/glib-types.h,$(wildcard src/glib/gobject/*.h)) \
    build/gobject-introspection/GLib-2.0.gir
	$(build_gir)

build/gobject-introspection/GModule-2.0.gir: \
    src/gobject-introspection/gir/gmodule-2.0.c \
    src/glib/gmodule/*.h \
    build/gobject-introspection/GLib-2.0.gir
	$(build_gir)

build/gobject-introspection/Gio-2.0.gir: \
    src/gobject-introspection/gir/gio-2.0.c \
    src/glib/gio/*.h \
    build/gobject-introspection/GObject-2.0.gir
	$(build_gir)
